# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

D_tilde_rcpp <- function(x) {
    .Call('_GFDmcv_D_tilde_rcpp', PACKAGE = 'GFDmcv', x)
}

Psi_est_rcpp <- function(x) {
    .Call('_GFDmcv_Psi_est_rcpp', PACKAGE = 'GFDmcv', x)
}

sigma_est_w_rccp <- function(x, w, mu_w) {
    .Call('_GFDmcv_sigma_est_w_rccp', PACKAGE = 'GFDmcv', x, w, mu_w)
}

sigma_est_ws_rccp <- function(x, w, mu_w) {
    .Call('_GFDmcv_sigma_est_ws_rccp', PACKAGE = 'GFDmcv', x, w, mu_w)
}

Psi_est_w_rcpp <- function(x, w) {
    .Call('_GFDmcv_Psi_est_w_rcpp', PACKAGE = 'GFDmcv', x, w)
}

